### ISSUE TITLE
Doesn't appear to be working as of 5/04/2022

### ISSUE THREAD

**Issue by ConanBa** [cheesestringer/salary-seeker#19]
![image](https://user-images.githubusercontent.com/43140772/161646257-606560dd-3d96-47b0-bfb4-af843754e883.png)

**Comment by cheesestringer** [comment]
Seems to be working ok, might have been a slow response. Can you try again and let me know if any issues?

![image](https://user-images.githubusercontent.com/4462478/161757563-48c1ebb7-4b30-4302-bb37-a860d0efd7aa.png)

**Comment by ConanBa** [comment]
That's strange it's still not working for me. 

I'm on Chrome

![image](https://user-images.githubusercontent.com/43140772/161862165-bb235394-e1fa-4959-a2c5-d0c5fbdab1d7.png)

If I got to a job for example https://www.seek.com.au/job/56518595?savedSearchID=be8473a6-1cb2-11eb-8e69-7fbfea11ce48&type=promoted&tracking=JMC-SAU-eDM-SEEKSelectTop1-6670

It doesn't come up for me.

I'm running this version and it's enabled

![image](https://user-images.githubusercontent.com/43140772/161862498-4bf2d769-98fe-4f52-85c9-a7bc17aa92dd.png)

I cleared browsing history and cookies etc but It's still not working

**Comment by cheesestringer** [comment]
I'll take a closer look on Chrome then. In the mean time if you click on the extension icon in the nav bar are you able to see the salary there?

![image](https://user-images.githubusercontent.com/4462478/161900966-583e07c6-7433-458b-a0a0-27cbc05b8a79.png)

**Comment by ConanBa** [comment]
It's popping up now.

whatever you did seems to have fixed it

![image](https://user-images.githubusercontent.com/43140772/161906094-3170d164-e876-489a-bee4-ec286720efef.png)

**Comment by cheesestringer** [comment]
Awesome glad to hear it's working again! Sometimes Seek changes the layout which can mess with the extension. Pressing the salary icon to view job history is a good work around.
