### ISSUE TITLE
Firefox link in README is dead, and can't find extension in searching in the store.

### ISSUE THREAD

**Issue by josh-sukheja** [cheesestringer/salary-seeker#20]
Title 😢

**Comment by cheesestringer** [comment]
Thanks for reporting! Looking in to this now.

**Comment by cheesestringer** [comment]
Looks like Firefox pulled this due to some new policy changes around minified files. I've resubmitted and hopefully this will be up again soon.

**Comment by cheesestringer** [comment]
Has been republished, let me know if you have any issues
