### ISSUE TITLE
New Ads posted on Seek.com.au aren't displaying salary correctly

### ISSUE THREAD

**Issue by jackienopants** [cheesestringer/salary-seeker#21]
It appears ad posted on seek.com.au since 28th July aren't displaying the salary range, the message that appears is:
Salary (estimated): Failed to calculate salary range: Unexpected token < in JSON at position 0
Tested previous days and they all still appear to be working.

**Comment by cheesestringer** [comment]
Thanks for the report! Do you have an example job url? Will start looking in to this soon.

**Comment by cheesestringer** [comment]
Haven't been able to replicate this so closing for now. If it happens again feel free to re-open this issue and send through the job url so I can take a look.
