### ISSUE TITLE
Higher Salaries Not Reporting Correctly

### ISSUE THREAD

**Issue by Matty-AUS** [cheesestringer/salary-seeker#22]
After receiving an email from seek regarding being able to search higher salary brackets, I thought I'd give it a go.

![Higher brackets](https://user-images.githubusercontent.com/23118120/184275455-f3ca466d-a94e-422e-b15b-12c478e5c030.png)

I then noticed some discrepancies and think the extension may need an udpate

For example, there is this job, which clearly indicate the salary in the ad, and is visible when 350k+ is selected as a filter, however the extension is reporting  $189,000 - $195,000

https://www.seek.com.au/job/58055183?type=standout#sol=9b2554a2ea81eed02d25f558aecccf584496db51

![Salary Seeker](https://user-images.githubusercontent.com/23118120/184275151-7b54a06c-c5fc-41ad-8312-7fc6128d22a4.png)

**Comment by cheesestringer** [comment]
Thanks for raising an issue! You're right, now that Seek is supporting larger salaries I need to update the max range.

**Comment by cheesestringer** [comment]
Seek sets the upper range at 350k to 999k.

![image](https://user-images.githubusercontent.com/4462478/184604450-38ada40a-4968-4800-a1d0-5b3678b066b2.png)

Annoyingly jobs in this range seem to always have a maximum of 999k.
![image](https://user-images.githubusercontent.com/4462478/184604749-6fe8cbb7-157b-46bf-a35f-ed1a7e97c378.png)

**Comment by cheesestringer** [comment]
New version is published but the upper end of the range will be super inaccurate.

**Comment by Matty-AUS** [comment]
> New version is published but the upper end of the range will be super inaccurate.

Super speedy response/rectification.

I noticed that SEEK's own filters don't work properly for the higher ranges
