### ISSUE TITLE
Salary (estimated): Failed to calculate salary range: Unsuccessful response: 500

### ISSUE THREAD

**Issue by iamrodtaylor** [cheesestringer/salary-seeker#26]
Hi, just installed the extension and all jobs are showing like this. I tried refreshing the page several times, disabled my adblocker and it also doesn't show any jobs in the recent list.

![image](https://user-images.githubusercontent.com/53284137/213567185-5615458c-40ae-4051-ac8b-63b196d8b4e0.png)

Cheers

**Comment by iamrodtaylor** [comment]
Sorry, another ad blocker was blocking it. All sorted now

**Comment by cheesestringer** [comment]
Thanks for letting me know, which one was it? I'll take a look at their block list and see if it can be updated.

**Comment by iamrodtaylor** [comment]
It was AdGuard and this is the exception string to unblock
@@||jobsearch-api.cloud.seek.com.au/search^

Cheers
