### ISSUE TITLE
Failed to calculate salary range: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by josh-sukheja** [cheesestringer/salary-seeker#27]
**URL**
Just one example:
https://www.seek.com.au/job/67210946

**Browser**
Firefox 112

**Description**
Seems to be happening on every job I've clicked on today:
```
Salary (estimated): Failed to calculate salary range: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```
![image](https://user-images.githubusercontent.com/45578963/235833422-c1e0d378-12bd-4d4b-8e11-682233b6f9ed.png)

**Comment by cheesestringer** [comment]
Thanks for reporting! I've got a fix in place and I'm just waiting for the extension store approvals.
