### ISSUE TITLE
Manifest json is in the wrong folder and Chrome won't side-load

### ISSUE THREAD

**Issue by thisistony** [cheesestringer/salary-seeker#29]
The manifest must be moved into the main folder or background.js moved into the Chrome folder. 

<img width="536" alt="image" src="https://github.com/user-attachments/assets/f02497f4-c346-4f18-ba8a-c39903dcc204">

<img width="551" alt="image" src="https://github.com/user-attachments/assets/eb1a15d5-b88f-4d44-8d93-03f38ae0310a">

**URL**
Provide the URL for the job. For example:
```
https://www.seek.com.au/job/12345678
```

**Browser**
Chrome, Firefox, Opera, or Edge

**Description**
Describe what bug you are seeing.

**Comment by cheesestringer** [comment]
The structure isn't the best for contributing but this will be fixed up soon in the V2 rebuild ✨
