### ISSUE TITLE
 On Firefox, salary keeps getting added over and over again.

### ISSUE THREAD

**Issue by quickreactor** [cheesestringer/salary-seeker#30]
**Browser**
 Firefox

**Description**
 The extension keeps adding the salary to the job multiple times.

![image](https://github.com/user-attachments/assets/8815ea31-02cb-40d6-82cf-d51e45fd2d7a)

**Comment by cheesestringer** [comment]
That's a different extension.

Salary seeker is published at https://addons.mozilla.org/en-US/firefox/addon/salary-seeker/
