### ISSUE TITLE
Failed to calculate salary range: JSON.parse: unexpected character at line 2 column 5 of the JSON data

### ISSUE THREAD

**Issue by BurgerFan45** [cheesestringer/salary-seeker#31]
**URL**
```
https://www.seek.com.au/job/80402339
```

**Browser**
Firefox

**Description**
Salary (estimated): Failed to calculate salary range: JSON.parse: unexpected character at line 2 column 5 of the JSON data
appears for every job.
![Screenshot 2024-11-28 093316](https://github.com/user-attachments/assets/ef1247e9-7a1e-412f-bfba-09b2eb7cf571)

**Comment by cheesestringer** [comment]
This is now fixed, just waiting for the stores to publish the update. Thanks for reporting!

**Comment by cheesestringer** [comment]
Firefox 2.0.1 update is now live 🎉

Let me know if you have any issues.

**Comment by gsosna** [comment]
Thank you cheesestringer. The Aussie one works now, but NZ now comes up with "Salary SeekerFailed to get price 😵"

**Comment by cheesestringer** [comment]
Good find, will look into this one when I get home

**Comment by cheesestringer** [comment]
Firefox 2.0.2 update is now live 🎉

Let me know if you have any issues.

**Comment by gsosna** [comment]
> Firefox 2.0.2 update is now live 🎉
> 
> Let me know if you have any issues.

It works! Thank you!!!
